language: ruby
rvm:
- 2.4.0
cache: bundler
sudo: false
script:
- bundle exec rake test
after_success:
- bundle exec codeclimate-test-reporter
env:
  global:
    secure: mx5SVAoJ6ZS3YeMLYtttC6fyg3+8VnJ8PVfQZrtWVJGi+7q4uPo6D9Et0PVDMDYv2LswueUxKfQ5t1TycmMUSaycDFKRaUye5SXUzmzXrNm99gg05KZX0+5w9ppqLILxQCHm6Ez7UWbbIp/yAuoik3MLnZea+rihIuJv6033bR4YA9LXMLTfIhcnG0VHgTN6GKqZl3ayG5sf5Yf+rRdLEgxuFoVeJC23/V0ctkSKjTq2DmZUpE5Geu+H8VjcqsJTpTX31WwiV0xQ1QKAZ75okdjOMSvF4sN62BpSr4rL8w08tZvR+iulU7TUkpWdW3K5yAFzw08ILCWUbk8gasYx0a6/xz0CtX1+8pZru6IvCbOKKZSd9aV+mGrNBMPsVEFDjr2la/0mlRFzzQabeGFy7vg8ZCOwlHkUR3bRyq8TQEFqRulds0QYv5rTe1bI5d5UAB4VW/9rVh58mL75DVnyaWbCiBPs0ZWqNjxBONI+rX8DQeH01+UGYk/CXuo7i4YGGml6L9As3VqBKcI+xhGaHTSuPYWzEHIwK9qs3buYKUGpBARHLTUJdf6bsx7qHOdhO0t+L9mwB8RhbdYGp3C3ZVtG1Y3riULnVZctjVLUvVy472wB2k4XikgW/VZU1EJpbs4ZwYr6/Ccr9Mpejq+BaklOYx/D8+ZueLz1y26p7lk=
